insert into hero values(11, 'Dr Nice' )
insert into hero values(12, 'Narco' )
insert into hero values(13, 'Bombasto' )
insert into hero values(14, 'Celeritas' )
insert into hero values(15, 'Magneta' )
insert into hero values(16, 'RubberMan' )
insert into hero values(17, 'Dynama' )
insert into hero values(18, 'Dr IQ' )
insert into hero values(19, 'Magma' )
insert into hero values(20, 'Tornado' )